const API = 'https://mercado-cloud-admin-production.up.railway.app'
const LANDINGS = {MX:'https://www.mercadolibre.com.mx/importados/compra-internacional',BR:'https://www.mercadolivre.com.br/importados/compra-internacional',CL:'https://www.mercadolibre.cl/importados/compra-internacional',CO:'https://www.mercadolibre.com.co/importados/compra-internacional'}
let busy = false
const sleep = ms => new Promise(r => setTimeout(r, ms))
async function saveState(patch){const {collectorState={}}=await chrome.storage.local.get('collectorState');await chrome.storage.local.set({collectorState:{...collectorState,...patch}})}
async function waitLoaded(tabId){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{chrome.tabs.onUpdated.removeListener(fn);reject(new Error('页面加载超时'))},60000);function fn(id,info){if(id===tabId&&info.status==='complete'){clearTimeout(timer);chrome.tabs.onUpdated.removeListener(fn);resolve()}}chrome.tabs.onUpdated.addListener(fn)})}
async function navigate(tabId,url){const waiting=waitLoaded(tabId);await chrome.tabs.update(tabId,{url,active:true});await waiting;await sleep(2500)}
async function runExtract(tabId,mode){const out=await chrome.scripting.executeScript({target:{tabId},func:mode==='landing'?extractLanding:extractListing});return out[0]?.result||{}}
async function upload(country,products){if(!products.length)return 0;const {collectorToken}=await chrome.storage.local.get('collectorToken');const r=await fetch(API+'/api/admin/international-import',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+collectorToken},body:JSON.stringify({country,products})});const d=await r.json();if(d.code!==0)throw new Error(d.message||'上传失败');return d.data.imported||0}
async function crawl(){if(busy)return;busy=true;try{
  let {collectorState:s={}}=await chrome.storage.local.get('collectorState');if(s.status!=='运行中')return
  let tab;if(s.tabId){try{tab=await chrome.tabs.get(s.tabId)}catch(e){}}if(!tab){tab=await chrome.tabs.create({url:LANDINGS[s.country],active:true});await saveState({tabId:tab.id});await waitLoaded(tab.id);await sleep(2500)}
  if(!s.queue?.length){await navigate(tab.id,LANDINGS[s.country]);const landing=await runExtract(tab.id,'landing');if(landing.blocked)throw new Error('需要登录或验证');s.queue=landing.categories;s.visited=[];await saveState({queue:s.queue,visited:[],message:`发现 ${s.queue.length} 个分类入口`})}
  while(s.status==='运行中'&&s.queue.length){const url=s.queue.shift();if(s.visited.includes(url))continue;await navigate(tab.id,url);const page=await runExtract(tab.id,'listing');if(page.blocked){s.queue.unshift(url);await saveState({queue:s.queue,status:'已暂停',message:'页面要求登录或验证码，请完成后继续'});return}
    const saved=await upload(s.country,page.products||[]);s.saved=(s.saved||0)+saved;s.pages=(s.pages||0)+1;s.visited.push(url);if(page.nextUrl&&!s.visited.includes(page.nextUrl))s.queue.push(page.nextUrl);await saveState({queue:s.queue,visited:s.visited,saved:s.saved,pages:s.pages,message:`剩余 ${s.queue.length} 个页面`});await sleep((s.delay||15)*1000+Math.floor(Math.random()*5000));({collectorState:s}=await chrome.storage.local.get('collectorState'))}
  if(!s.queue.length)await saveState({status:'已完成',message:'当前发现的分类和分页已全部处理'})
}catch(e){await saveState({status:'已暂停',message:e.message})}finally{busy=false}}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.type==='START'){chrome.storage.local.get('collectorState').then(({collectorState={}})=>saveState({country:m.country,delay:m.delay,status:'运行中',saved:collectorState.country===m.country?collectorState.saved||0:0,pages:collectorState.country===m.country?collectorState.pages||0:0,queue:collectorState.country===m.country?collectorState.queue||[]:[],visited:collectorState.country===m.country?collectorState.visited||[]:[],message:''})).then(crawl);reply({ok:true})}if(m.type==='STOP'){saveState({status:'已暂停',message:'用户手动暂停'});reply({ok:true})}return true})
chrome.alarms.create('resumeCrawler',{periodInMinutes:1});chrome.alarms.onAlarm.addListener(a=>{if(a.name==='resumeCrawler')crawl()})
function extractLanding(){const u=location.href;if(/account-verification|recaptcha|\/login\//i.test(u))return{blocked:true};const base=location.hostname.replace(/^www\./,'');const categories=[...document.querySelectorAll('a[href*="/importados/compra-internacional/"]')].map(a=>a.href.split('#')[0]).filter(x=>{try{return new URL(x).hostname.endsWith(base)}catch(e){return false}});return{blocked:false,categories:[...new Set(categories)]}}
function extractListing(){const u=location.href;if(/account-verification|recaptcha|\/login\//i.test(u)||/Para continuar|Para continuar|iniciar sesión|acesse sua conta/i.test(document.body.innerText))return{blocked:true};const categoryName=document.querySelector('h1')?.textContent?.trim()||document.title;const cards=[...document.querySelectorAll('.poly-card,.ui-search-result')];const products=cards.map(card=>{const a=card.querySelector('a.poly-component__title,a.ui-search-link,a[href*="international_context=true"]');if(!a)return null;const url=a.href;const id=(url.match(/[?&#]wid=(M[A-Z]{2}\d+)/)||url.match(/item_id%3A(M[A-Z]{2}\d+)/i)||url.match(/\/(M[A-Z]{2})-(\d+)-/))?.slice(1).join('');const img=card.querySelector('img');const amount=card.querySelector('[data-andes-money-amount-fraction]')?.textContent?.replace(/\D/g,'')||'';const cents=card.querySelector('[data-andes-money-amount-cents]')?.textContent?.replace(/\D/g,'')||'0';const currency=document.querySelector('meta[name="currency"]')?.content||({'.com.br':'BRL','.com.mx':'MXN','.cl':'CLP','.com.co':'COP'}[Object.keys({'.com.br':1,'.com.mx':1,'.cl':1,'.com.co':1}).find(x=>location.hostname.endsWith(x))]||'');return id?{itemId:id,title:a.textContent.trim(),price:Number(amount+'.'+cents),currency,discount:card.querySelector('.andes-money-amount__discount,.poly-component__discount')?.textContent?.trim()||'',imageUrl:img?.currentSrc||img?.src||img?.dataset?.src||'',productUrl:url,categoryName,categoryUrl:u,listingTime:null}:null}).filter(Boolean);const next=document.querySelector('.andes-pagination__button--next:not(.andes-pagination__button--disabled) a');return{blocked:false,products,nextUrl:next?.href||null}}
